handlebars:
  suffix: .html

server:
  tomcat:
    accept-count: 10 # work queue 사이즈
    max-connections: 20 # 최대 맺을 수 있는 커넥션 수 -> 동시 수용 가능한 요청 수
    threads:
      min-spare: 1 # 영향 없음
      max: 5 # 스레드 풀 개수 ->

  compression:
    enabled: True
    min-response-size: 1
